name: CI for NestJS Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Instalação de dependências
      - name: Install dependencies
        run: npm install

      # Rodando os testes
      - name: Run tests
        run: npm test

      # Verificando se a aplicação está compilando
      - name: Build application
        run: npm run build
